server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.135.133:3306/library?characterEncoding=utf-8
    username: root
    password: 123
